# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Utbk_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Utbk_iOS
    pod 'AFNetworking'
    pod 'MJExtension', '~> 3.0.10'
    pod 'Masonry'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'SDWebImage'
    pod 'MSCycleScrollView'
    pod 'TZImagePickerController','3.3.1'
    pod 'IQKeyboardManager'
    pod 'Toast', '2.0.0'
    pod 'CocoaAsyncSocket'
    pod 'VTMagic'
    pod 'YBPopupMenu', '~> 1.1.2'
    pod 'PGDatePicker'
end
